train_parameters:
  train_manifest: "/mnt/32mins/gender_detection/ekstep-language-identification/data/train.csv"
  valid_manifest: "/mnt/32mins/gender_detection/ekstep-language-identification/data/valid.csv"
  batch_size: 128
  learning_rate: 1e-3
  num_epochs: 100
  num_workers: 10
  num_classes: 2
  checkpoint_path: "/mnt/32mins/gender_detection/ekstep-language-identification/checkpoints"